import { compilerSlotSafe } from './compilerSlot';

export { default as createMemo } from './factory/createMemo';
export { default as createReducerContext } from './factory/createReducerContext';
export { default as createReducer } from './factory/createReducer';
export { default as createStateContext } from './factory/createStateContext';
import rawUseAsync from './useAsync';
export const useAsync = compilerSlotSafe(rawUseAsync);
import rawUseAsyncFn from './useAsyncFn';
export const useAsyncFn = compilerSlotSafe(rawUseAsyncFn);
import rawUseAsyncRetry from './useAsyncRetry';
export const useAsyncRetry = compilerSlotSafe(rawUseAsyncRetry);
import rawUseAudio from './useAudio';
export const useAudio = compilerSlotSafe(rawUseAudio);
import rawUseBattery from './useBattery';
export const useBattery = compilerSlotSafe(rawUseBattery);
import rawUseBeforeUnload from './useBeforeUnload';
export const useBeforeUnload = compilerSlotSafe(rawUseBeforeUnload);
import rawUseBoolean from './useBoolean';
export const useBoolean = compilerSlotSafe(rawUseBoolean);
import rawUseClickAway from './useClickAway';
export const useClickAway = compilerSlotSafe(rawUseClickAway);
import rawUseCookie from './useCookie';
export const useCookie = compilerSlotSafe(rawUseCookie);
import rawUseCopyToClipboard from './useCopyToClipboard';
export const useCopyToClipboard = compilerSlotSafe(rawUseCopyToClipboard);
import rawUseCounter from './useCounter';
export const useCounter = compilerSlotSafe(rawUseCounter);
import rawUseCss from './useCss';
export const useCss = compilerSlotSafe(rawUseCss);
import rawUseCustomCompareEffect from './useCustomCompareEffect';
export const useCustomCompareEffect = compilerSlotSafe(rawUseCustomCompareEffect);
import rawUseDebounce from './useDebounce';
export const useDebounce = compilerSlotSafe(rawUseDebounce);
import rawUseDeepCompareEffect from './useDeepCompareEffect';
export const useDeepCompareEffect = compilerSlotSafe(rawUseDeepCompareEffect);
import rawUseDefault from './useDefault';
export const useDefault = compilerSlotSafe(rawUseDefault);
import rawUseDrop from './useDrop';
export const useDrop = compilerSlotSafe(rawUseDrop);
import rawUseDropArea from './useDropArea';
export const useDropArea = compilerSlotSafe(rawUseDropArea);
import rawUseEffectOnce from './useEffectOnce';
export const useEffectOnce = compilerSlotSafe(rawUseEffectOnce);
import rawUseEnsuredForwardedRef, { ensuredForwardRef } from './useEnsuredForwardedRef';
export const useEnsuredForwardedRef = compilerSlotSafe(rawUseEnsuredForwardedRef);
export { ensuredForwardRef };
import rawUseEvent from './useEvent';
export const useEvent = compilerSlotSafe(rawUseEvent);
import rawUseError from './useError';
export const useError = compilerSlotSafe(rawUseError);
import rawUseFavicon from './useFavicon';
export const useFavicon = compilerSlotSafe(rawUseFavicon);
import rawUseFullscreen from './useFullscreen';
export const useFullscreen = compilerSlotSafe(rawUseFullscreen);
import rawUseGeolocation from './useGeolocation';
export const useGeolocation = compilerSlotSafe(rawUseGeolocation);
import rawUseGetSet from './useGetSet';
export const useGetSet = compilerSlotSafe(rawUseGetSet);
import rawUseGetSetState from './useGetSetState';
export const useGetSetState = compilerSlotSafe(rawUseGetSetState);
import rawUseHarmonicIntervalFn from './useHarmonicIntervalFn';
export const useHarmonicIntervalFn = compilerSlotSafe(rawUseHarmonicIntervalFn);
import rawUseHover from './useHover';
export const useHover = compilerSlotSafe(rawUseHover);
import rawUseHoverDirty from './useHoverDirty';
export const useHoverDirty = compilerSlotSafe(rawUseHoverDirty);
import rawUseIdle from './useIdle';
export const useIdle = compilerSlotSafe(rawUseIdle);
import rawUseIntersection from './useIntersection';
export const useIntersection = compilerSlotSafe(rawUseIntersection);
import rawUseInterval from './useInterval';
export const useInterval = compilerSlotSafe(rawUseInterval);
import rawUseIsomorphicLayoutEffect from './useIsomorphicLayoutEffect';
export const useIsomorphicLayoutEffect = compilerSlotSafe(rawUseIsomorphicLayoutEffect);
import rawUseKey from './useKey';
export const useKey = compilerSlotSafe(rawUseKey);
export { default as createBreakpoint } from './factory/createBreakpoint';
// not exported because of peer dependency
// export { default as useKeyboardJs } from './useKeyboardJs';
import rawUseKeyPress from './useKeyPress';
export const useKeyPress = compilerSlotSafe(rawUseKeyPress);
import rawUseKeyPressEvent from './useKeyPressEvent';
export const useKeyPressEvent = compilerSlotSafe(rawUseKeyPressEvent);
import rawUseLatest from './useLatest';
export const useLatest = compilerSlotSafe(rawUseLatest);
import rawUseLifecycles from './useLifecycles';
export const useLifecycles = compilerSlotSafe(rawUseLifecycles);
import rawUseList from './useList';
export const useList = compilerSlotSafe(rawUseList);
import rawUseLocalStorage from './useLocalStorage';
export const useLocalStorage = compilerSlotSafe(rawUseLocalStorage);
import rawUseLocation from './useLocation';
export const useLocation = compilerSlotSafe(rawUseLocation);
import rawUseLockBodyScroll from './useLockBodyScroll';
export const useLockBodyScroll = compilerSlotSafe(rawUseLockBodyScroll);
import rawUseLogger from './useLogger';
export const useLogger = compilerSlotSafe(rawUseLogger);
import rawUseLongPress from './useLongPress';
export const useLongPress = compilerSlotSafe(rawUseLongPress);
import rawUseMap from './useMap';
export const useMap = compilerSlotSafe(rawUseMap);
import rawUseMedia from './useMedia';
export const useMedia = compilerSlotSafe(rawUseMedia);
import rawUseMediaDevices from './useMediaDevices';
export const useMediaDevices = compilerSlotSafe(rawUseMediaDevices);
import { useMediatedState as rawUseMediatedState } from './useMediatedState';
export const useMediatedState = compilerSlotSafe(rawUseMediatedState);
import rawUseMethods from './useMethods';
export const useMethods = compilerSlotSafe(rawUseMethods);
import rawUseMotion from './useMotion';
export const useMotion = compilerSlotSafe(rawUseMotion);
import rawUseMount from './useMount';
export const useMount = compilerSlotSafe(rawUseMount);
import rawUseMountedState from './useMountedState';
export const useMountedState = compilerSlotSafe(rawUseMountedState);
import rawUseMouse from './useMouse';
export const useMouse = compilerSlotSafe(rawUseMouse);
import rawUseMouseHovered from './useMouseHovered';
export const useMouseHovered = compilerSlotSafe(rawUseMouseHovered);
import rawUseMouseWheel from './useMouseWheel';
export const useMouseWheel = compilerSlotSafe(rawUseMouseWheel);
import rawUseNetworkState from './useNetworkState';
export const useNetworkState = compilerSlotSafe(rawUseNetworkState);
import rawUseNumber from './useNumber';
export const useNumber = compilerSlotSafe(rawUseNumber);
import rawUseObservable from './useObservable';
export const useObservable = compilerSlotSafe(rawUseObservable);
import rawUseOrientation from './useOrientation';
export const useOrientation = compilerSlotSafe(rawUseOrientation);
import rawUsePageLeave from './usePageLeave';
export const usePageLeave = compilerSlotSafe(rawUsePageLeave);
import rawUsePermission from './usePermission';
export const usePermission = compilerSlotSafe(rawUsePermission);
import rawUsePrevious from './usePrevious';
export const usePrevious = compilerSlotSafe(rawUsePrevious);
import rawUsePreviousDistinct from './usePreviousDistinct';
export const usePreviousDistinct = compilerSlotSafe(rawUsePreviousDistinct);
import rawUsePromise from './usePromise';
export const usePromise = compilerSlotSafe(rawUsePromise);
import rawUseQueue from './useQueue';
export const useQueue = compilerSlotSafe(rawUseQueue);
import rawUseRaf from './useRaf';
export const useRaf = compilerSlotSafe(rawUseRaf);
import rawUseRafLoop from './useRafLoop';
export const useRafLoop = compilerSlotSafe(rawUseRafLoop);
import rawUseRafState from './useRafState';
export const useRafState = compilerSlotSafe(rawUseRafState);
import rawUseSearchParam from './useSearchParam';
export const useSearchParam = compilerSlotSafe(rawUseSearchParam);
import rawUseScratch from './useScratch';
export const useScratch = compilerSlotSafe(rawUseScratch);
import rawUseScroll from './useScroll';
export const useScroll = compilerSlotSafe(rawUseScroll);
import rawUseScrolling from './useScrolling';
export const useScrolling = compilerSlotSafe(rawUseScrolling);
import rawUseSessionStorage from './useSessionStorage';
export const useSessionStorage = compilerSlotSafe(rawUseSessionStorage);
import rawUseSetState from './useSetState';
export const useSetState = compilerSlotSafe(rawUseSetState);
import rawUseShallowCompareEffect from './useShallowCompareEffect';
export const useShallowCompareEffect = compilerSlotSafe(rawUseShallowCompareEffect);
import rawUseSize from './useSize';
export const useSize = compilerSlotSafe(rawUseSize);
import rawUseSlider from './useSlider';
export const useSlider = compilerSlotSafe(rawUseSlider);
import rawUseSpeech from './useSpeech';
export const useSpeech = compilerSlotSafe(rawUseSpeech);
// not exported because of peer dependency
// export { default as useSpring } from './useSpring';
import rawUseStartTyping from './useStartTyping';
export const useStartTyping = compilerSlotSafe(rawUseStartTyping);
import { useStateWithHistory as rawUseStateWithHistory } from './useStateWithHistory';
export const useStateWithHistory = compilerSlotSafe(rawUseStateWithHistory);
import rawUseStateList from './useStateList';
export const useStateList = compilerSlotSafe(rawUseStateList);
import rawUseThrottle from './useThrottle';
export const useThrottle = compilerSlotSafe(rawUseThrottle);
import rawUseThrottleFn from './useThrottleFn';
export const useThrottleFn = compilerSlotSafe(rawUseThrottleFn);
import rawUseTimeout from './useTimeout';
export const useTimeout = compilerSlotSafe(rawUseTimeout);
import rawUseTimeoutFn from './useTimeoutFn';
export const useTimeoutFn = compilerSlotSafe(rawUseTimeoutFn);
import rawUseTitle from './useTitle';
export const useTitle = compilerSlotSafe(rawUseTitle);
import rawUseToggle from './useToggle';
export const useToggle = compilerSlotSafe(rawUseToggle);
import rawUseTween from './useTween';
export const useTween = compilerSlotSafe(rawUseTween);
import rawUseUnmount from './useUnmount';
export const useUnmount = compilerSlotSafe(rawUseUnmount);
import rawUseUnmountPromise from './useUnmountPromise';
export const useUnmountPromise = compilerSlotSafe(rawUseUnmountPromise);
import rawUseUpdate from './useUpdate';
export const useUpdate = compilerSlotSafe(rawUseUpdate);
import rawUseUpdateEffect from './useUpdateEffect';
export const useUpdateEffect = compilerSlotSafe(rawUseUpdateEffect);
import rawUseUpsert from './useUpsert';
export const useUpsert = compilerSlotSafe(rawUseUpsert);
import rawUseVibrate from './useVibrate';
export const useVibrate = compilerSlotSafe(rawUseVibrate);
import rawUseVideo from './useVideo';
export const useVideo = compilerSlotSafe(rawUseVideo);
import rawUseStateValidator from './useStateValidator';
export const useStateValidator = compilerSlotSafe(rawUseStateValidator);
import { useScrollbarWidth as rawUseScrollbarWidth } from './useScrollbarWidth';
export const useScrollbarWidth = compilerSlotSafe(rawUseScrollbarWidth);
import { useMultiStateValidator as rawUseMultiStateValidator } from './useMultiStateValidator';
export const useMultiStateValidator = compilerSlotSafe(rawUseMultiStateValidator);
import rawUseWindowScroll from './useWindowScroll';
export const useWindowScroll = compilerSlotSafe(rawUseWindowScroll);
import rawUseWindowSize from './useWindowSize';
export const useWindowSize = compilerSlotSafe(rawUseWindowSize);
import rawUseMeasure from './useMeasure';
export const useMeasure = compilerSlotSafe(rawUseMeasure);
import rawUsePinchZoom from './usePinchZoom';
export const usePinchZoom = compilerSlotSafe(rawUsePinchZoom);
import { useRendersCount as rawUseRendersCount } from './useRendersCount';
export const useRendersCount = compilerSlotSafe(rawUseRendersCount);
import { useFirstMountState as rawUseFirstMountState } from './useFirstMountState';
export const useFirstMountState = compilerSlotSafe(rawUseFirstMountState);
import rawUseSet from './useSet';
export const useSet = compilerSlotSafe(rawUseSet);
export { createGlobalState } from './factory/createGlobalState';
import { useHash as rawUseHash } from './useHash';
export const useHash = compilerSlotSafe(rawUseHash);
