export type RechartsProps = Record<string, any>;

export type AreaProps<DataPointType = any, ValueAxisType = any> = RechartsProps;
export type BarProps = RechartsProps;
export type BarShapeProps = RechartsProps;
export type BrushProps = RechartsProps;
export type CartesianGridProps = RechartsProps;
export type DefaultLegendContentProps = RechartsProps;
export type DefaultTooltipContentProps = RechartsProps;
export type DotProps = RechartsProps;
export type ErrorBarProps = RechartsProps;
export type FunnelProps = RechartsProps;
export type LabelListProps = RechartsProps;
export type LabelProps = RechartsProps;
export type LegendProps = RechartsProps;
export type LineProps = RechartsProps;
export type PieLabel = (props: RechartsProps) => unknown;
export type PieProps<DataPointType = any, DataValueType = any> = RechartsProps;
export type PolarAngleAxisProps = RechartsProps;
export type PolarGridProps = RechartsProps;
export type PolarRadiusAxisProps = RechartsProps;
export type RadarProps = RechartsProps;
export type RadialBarProps = RechartsProps;
export type ReferenceLineProps = RechartsProps;
export type ResponsiveContainerProps = RechartsProps;
export type SankeyProps = RechartsProps;
export type ScatterProps = RechartsProps;
export type SunburstChartProps = RechartsProps;
export type TooltipProps<ValueType = any, NameType = any> = RechartsProps;
export type TreemapProps = RechartsProps;
export type XAxisProps = RechartsProps;
export type YAxisProps = RechartsProps;
export type ZAxisProps = RechartsProps;
export type TooltipFormatter = (...args: any[]) => unknown;
export type NameType = string | number;
export type ValueType = string | number | Array<string | number>;

export declare const AnimationControllerProvider: any;
export declare const Area: any;
export declare const AreaChart: any;
export declare const Bar: any;
export declare const BarChart: any;
export declare const BarStack: any;
export declare const Brush: any;
export declare const CartesianAxis: any;
export declare const CartesianChart: any;
export declare const CartesianGrid: any;
export declare const Cell: any;
export declare const ComposedChart: any;
export declare const Cross: any;
export declare const Curve: any;
export declare const DefaultLegendContent: any;
export declare const DefaultTooltipContent: any;
export declare const Dot: any;
export declare const ErrorBar: any;
export declare const Funnel: any;
export declare const FunnelChart: any;
export declare const Label: any;
export declare const LabelList: any;
export declare const Layer: any;
export declare const Legend: any;
export declare const Line: any;
export declare const LineChart: any;
export declare const LineDrawShape: any;
export declare const Pie: any;
export declare const PieChart: any;
export declare const PolarAngleAxis: any;
export declare const PolarGrid: any;
export declare const PolarRadiusAxis: any;
export declare const Polygon: any;
export declare const Radar: any;
export declare const RadarChart: any;
export declare const RadialBar: any;
export declare const RadialBarChart: any;
export declare const Rectangle: any;
export declare const ReferenceLine: any;
export declare const ResponsiveContainer: any;
export declare const Sankey: any;
export declare const Scatter: any;
export declare const ScatterChart: any;
export declare const Sector: any;
export declare const SunburstChart: any;
export declare const Surface: any;
export declare const Symbols: any;
export declare const Text: any;
export declare const Tooltip: any;
export declare const Trapezoid: any;
export declare const XAxis: any;
export declare const YAxis: any;
export declare const ZAxis: any;
export declare const ZIndexLayer: any;

export declare const useActiveTooltipDataPoints: any;
export declare const useActiveTooltipLabel: any;
export declare const useCartesianChartLayout: any;
export declare const useChartHeight: any;
export declare const useChartLayout: any;
export declare const useChartWidth: any;
export declare const useIsInChartContext: any;
export declare const useMargin: any;
export declare const useOffset: any;
export declare const usePlotArea: any;
export declare const usePolarChartLayout: any;
export declare const useViewBox: any;
export declare const useXAxis: any;
export declare const useXAxisInverseScale: any;
export declare const useXAxisScale: any;
export declare const useYAxis: any;
export declare const useYAxisInverseScale: any;
export declare const useYAxisScale: any;
